export const projects = [
    {title: "test 1",
        description: "lorem isadiadoa csiacaoiscans",
        tags: ["React","Tailwind"],
        liveUrl: "x",
        githubUrl: "x",
    },
    {title: "",
        description: "",
        tags: ["",""],
        liveUrl: "",
        githubUrl: "",
    },
    {title: "",
        description: "",
        tags: ["",""],
        liveUrl: "",
        githubUrl: "",
    },
    {title: "",
        description: "",
        tags: ["",""],
        liveUrl: "",
        githubUrl: "",
    },
    {title: "",
        description: "",
        tags: ["",""],
        liveUrl: "",
        githubUrl: "",
    },
    {title: "",
        description: "",
        tags: ["",""],
        liveUrl: "",
        githubUrl: "",
    },
]